// generated by chatGPT

export type Location = {
    id: number
    name: string
    address?: string
    website?: string
    events: Event[]
    createdAt: Date
    updatedAt: Date
  }
  
  export type Event = {
    id: number
    eventId: number
    name: string
    description?: string
    cost: number
    minAge: number
    maxAge: number
    location: Location
    locationId: number
    day: string[],
    startTime: string
    endTime: string
    termTime: boolean
    createdAt: Date
    updatedAt: Date
    website?: string
    phone?: string
    email?: string
    tags: Tag[]
  }
  
  export type Tag = {
    id: number
    tagId: number
    name: string
    description?: string
    events: Event[]
    createdAt: Date
    updatedAt: Date
  }
  
  export enum Day {
    Sunday = 'Sunday',
    Monday = 'Monday',
    Tuesday = 'Tuesday',
    Wednesday = 'Wednesday',
    Thursday = 'Thursday',
    Friday = 'Friday',
    Saturday = 'Saturday'
  }
  