// import { EventWithLocation } from '../../src/types/EventWithLocation';

import { Event, Location } from '.prisma/client/index.d';

export interface EventWithLocation extends Event {
	location: Location;
}

export const mockEvent: EventWithLocation = {
	id: 1,
	eventId: 123,
	name: 'Example Event',
	description: 'This is an example event',
	cost: 10,
	donation: false,
	familyGroup: true,
	siblingDiscount: true,
	minAgeMonths: 0,
	minAgeYears: 3,
	maxAgeMonths: 11,
	maxAgeYears: 8,
	day: ['Monday'],
	startTime: '10:00',
	endTime: '12:00',
	termTime: true,
	createdAt: new Date(),
	updatedAt: new Date(),
	website: 'https://example.com',
	phone: '0234567890',
	bookingRequired: true,
	email: 'example@example.com',
	locationId: 1,
	location: {
		id: 1,
		name: 'Example Location',
		address: '123 Main St',
		website: 'https://examplelocation.com',
		phone: '+1234567890',
		lat: 123.456,
		lng: 789.012,
		createdAt: new Date(),
		updatedAt: new Date(),
	},
};

export const mockEvents: EventWithLocation[] = [
	{
		id: 1,
		eventId: 123,
		name: 'Event 1',
		description: 'This is event 1',
		cost: 10,
		donation: false,
		familyGroup: true,
		siblingDiscount: true,
		minAgeMonths: 0,
		minAgeYears: 3,
		maxAgeMonths: 11,
		maxAgeYears: 8,
		day: ['Monday'],
		startTime: '10:00',
		endTime: '12:00',
		termTime: true,
		createdAt: new Date(),
		updatedAt: new Date(),
		website: 'https://example.com',
		phone: '0234567890',
		bookingRequired: true,
		email: 'example@example.com',
		locationId: 1,
		location: {
			id: 1,
			name: 'Location 1',
			address: '123 Main St',
			website: 'https://examplelocation1.com',
			phone: '+1234567890',
			lat: 123.456,
			lng: 789.012,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
	},
	{
		id: 2,
		eventId: 456,
		name: 'Event 2',
		description: 'This is event 2',
		cost: 20,
		donation: true,
		familyGroup: false,
		siblingDiscount: false,
		minAgeMonths: 12,
		minAgeYears: 4,
		maxAgeMonths: 36,
		maxAgeYears: 10,
		day: ['Tuesday'],
		startTime: '14:00',
		endTime: '16:00',
		termTime: false,
		createdAt: new Date(),
		updatedAt: new Date(),
		website: 'https://example2.com',
		phone: '0456789012',
		bookingRequired: false,
		email: 'example2@example.com',
		locationId: 2,
		location: {
			id: 2,
			name: 'Location 2',
			address: '456 Elm St',
			website: 'https://examplelocation2.com',
			phone: '+2345678901',
			lat: 456.789,
			lng: 901.234,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
	},
	{
		id: 3,
		eventId: 789,
		name: 'Event 3',
		description: 'This is event 3',
		cost: 30,
		donation: false,
		familyGroup: true,
		siblingDiscount: true,
		minAgeMonths: 24,
		minAgeYears: 6,
		maxAgeMonths: 48,
		maxAgeYears: 12,
		day: ['Wednesday'],
		startTime: '18:00',
		endTime: '20:00',
		termTime: true,
		createdAt: new Date(),
		updatedAt: new Date(),
		website: 'https://example3.com',
		phone: '0678901234',
		bookingRequired: true,
		email: 'event3@test.com',
		locationId: 3,
		location: {
			id: 3,
			name: 'Location 3',
			address: '789 Oak St',
			website: 'https://examplelocation3.com',
			phone: '+3456789012',
			lat: 789.012,
			lng: 123.456,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
	},
	{
		id: 4,
		eventId: 101,
		name: 'Event 4',
		description: 'This is event 4',
		cost: 40,
		donation: true,
		familyGroup: false,
		siblingDiscount: false,
		minAgeMonths: 36,
		minAgeYears: 8,
		maxAgeMonths: 60,
		maxAgeYears: 14,
		day: ['Thursday'],
		startTime: '10:00',
		endTime: '12:00',
		termTime: false,
		createdAt: new Date(),
		updatedAt: new Date(),
		website: 'https://example4.com',
		phone: '0789012345',
		bookingRequired: false,
		email: 'event4@event4.com',
		locationId: 4,
		location: {
			id: 4,
			name: 'Location 4',
			address: '101 Pine St',
			website: 'https://examplelocation4.com',
			phone: '+4567890123',
			lat: 901.234,
			lng: 234.567,
			createdAt: new Date(),
			updatedAt: new Date(),
		},
	},
];
